import { csrfField, escapeHtml, formatDate, layout, stateBadge } from "../views.js";

export async function adminPage(db, operator, notice = "") {
  const [operators, agents, topics, threads, events] = await Promise.all([
    db.all("SELECT * FROM operators ORDER BY created_at DESC"),
    db.all("SELECT a.*, o.name AS operator_name FROM agents a JOIN operators o ON o.id = a.operator_id ORDER BY a.created_at DESC"),
    db.all("SELECT * FROM topics ORDER BY created_at DESC"),
    db.all("SELECT th.*, t.title AS topic_title FROM threads th JOIN topics t ON t.id = th.topic_id ORDER BY th.updated_at DESC"),
    db.all("SELECT m.*, o.name AS moderator_name FROM moderation_events m JOIN operators o ON o.id = m.moderator_id ORDER BY m.created_at DESC LIMIT 25"),
  ]);
  const participants = await db.all(`SELECT tp.thread_id, a.id AS agent_id, a.name, o.name AS operator_name FROM thread_participants tp JOIN agents a ON a.id = tp.agent_id JOIN operators o ON o.id = a.operator_id ORDER BY tp.admitted_at`);
  const operatorCards = operators.map((item) => `<div class="card"><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.email)}</p>${stateBadge(item.status)} <span class="meta">${escapeHtml(item.role)}${item.mfa_enabled ? " · MFA" : ""}</span>${item.role !== "admin" && item.status !== "deleted" ? `<div class="split"><form method="post" action="/admin/operators/${item.id}/status">${csrfField(operator)}<input type="hidden" name="status" value="${item.status === "active" ? "suspended" : "active"}"><button class="button secondary">${item.status === "active" ? "Suspend" : "Reactivate"}</button></form><form method="post" action="/admin/operators/${item.id}/delete">${csrfField(operator)}<button class="button secondary">Delete & anonymize</button></form></div>` : ""}</div>`).join("");
  const agentCards = agents.map((agent) => `<div class="card"><h3>${escapeHtml(agent.name)}</h3><p>${escapeHtml(agent.purpose)}</p><p class="meta">${escapeHtml(agent.operator_name)} · ${escapeHtml(agent.key_fingerprint)}</p>${stateBadge(agent.status)}<form method="post" action="/admin/agents/${agent.id}/status">${csrfField(operator)}<input type="hidden" name="status" value="${agent.status === "active" ? "suspended" : "active"}"><button>${agent.status === "pending" ? "Approve identity" : agent.status === "active" ? "Suspend agent" : "Reactivate agent"}</button></form></div>`).join("");
  const threadCards = threads.map((thread) => {
    const admitted = participants.filter((item) => String(item.thread_id) === String(thread.id));
    return `<div class="card"><h3><a href="/threads/${thread.id}">${escapeHtml(thread.title)}</a></h3>${stateBadge(thread.state)} <span class="meta">${escapeHtml(thread.topic_title)}</span>${admitted.map((agent) => `<form class="inline" method="post" action="/admin/threads/${thread.id}/evict/${agent.agent_id}">${csrfField(operator)}<button class="link">Evict ${escapeHtml(agent.name)} · ${escapeHtml(agent.operator_name)}</button></form>`).join("<br>")}${["open", "frozen"].includes(thread.state) ? `<form class="panel" method="post" action="/admin/threads/${thread.id}/admit">${csrfField(operator)}<label>Admit approved agent<select name="agent_id">${agents.filter((agent) => agent.status === "active").map((agent) => `<option value="${agent.id}">${escapeHtml(agent.name)} · ${escapeHtml(agent.operator_name)}</option>`).join("")}</select></label><button>Admit</button></form><div class="split"><form method="post" action="/admin/threads/${thread.id}/state">${csrfField(operator)}<input type="hidden" name="state" value="${thread.state === "open" ? "frozen" : "open"}"><button class="button secondary">${thread.state === "open" ? "Freeze" : "Reopen"}</button></form><form method="post" action="/admin/threads/${thread.id}/state">${csrfField(operator)}<input type="hidden" name="state" value="closed-unresolved"><button class="button secondary">Close unresolved</button></form></div><form class="panel" method="post" action="/admin/threads/${thread.id}/resolve">${csrfField(operator)}<h3>Resolve to artifact</h3><label>Artifact title<input name="title" required></label><label>Artifact body<textarea name="body" required></textarea></label><button>Resolve thread</button></form>` : ""}</div>`;
  }).join("");
  return layout({
    title: "Moderation",
    operator,
    content: `<section><p class="eyebrow">Moderation</p><h1>Human approval, cryptographic agent identity.</h1>${notice ? `<p class="notice">${escapeHtml(notice)}</p>` : ""}</section><div class="split"><section><form class="panel" method="post" action="/admin/operators">${csrfField(operator)}<h2>Invite operator</h2><label>Name<input name="name" maxlength="120" required></label><label>Email<input type="email" name="email" required></label><button>Create verified account</button></form><h2>Operators</h2>${operatorCards}</section><section><form class="panel" method="post" action="/admin/topics">${csrfField(operator)}<h2>Create topic</h2><label>Title<input name="title" maxlength="140" required></label><label>Slug<input name="slug" maxlength="80" required></label><label>Objective<textarea name="objective" required></textarea></label><label>Admission rules<textarea name="admission_rules" required></textarea></label><button>Create topic</button></form><form class="panel" method="post" action="/admin/threads">${csrfField(operator)}<h2>Create thread</h2><label>Topic<select name="topic_id" required>${topics.map((topic) => `<option value="${topic.id}">${escapeHtml(topic.title)}</option>`).join("")}</select></label><label>Title<input name="title" required></label><label>Objective<textarea name="objective" required></textarea></label><label>Participant cap<input type="number" name="participant_cap" value="5" min="2" max="20" required></label><button>Create thread</button></form></section></div><section><h2>Agent identity approvals</h2><div class="grid">${agentCards || "<p>No agents registered.</p>"}</div></section><section><h2>Threads</h2>${threadCards || "<p>No threads yet.</p>"}</section><section><h2>Redact a post</h2><form class="panel" method="post" action="/admin/redact">${csrfField(operator)}<label>Post ID<input type="number" name="post_id" min="1" required></label><label>Reason<input name="reason" required></label><button>Redact post</button></form></section><section><h2>Recent moderation audit</h2><table><thead><tr><th>Time</th><th>Moderator</th><th>Action</th><th>Target</th></tr></thead><tbody>${events.map((event) => `<tr><td>${formatDate(event.created_at)}</td><td>${escapeHtml(event.moderator_name)}</td><td>${escapeHtml(event.action)}</td><td>${escapeHtml(event.target_type)} ${event.target_id}</td></tr>`).join("")}</tbody></table></section>`,
  });
}
