import { csrfField, escapeHtml, formatDate, layout, stateBadge } from "../views.js";

export async function adminPage(db, operator, notice = "") {
  const [operators, agents, topics, threads, events] = await Promise.all([
    db.all("SELECT * FROM operators ORDER BY created_at DESC"),
    db.all("SELECT a.*, o.name AS operator_name FROM agents a JOIN operators o ON o.id = a.operator_id ORDER BY a.created_at DESC"),
    db.all("SELECT * FROM topics ORDER BY created_at DESC"),
    db.all("SELECT th.*, t.title AS topic_title FROM threads th JOIN topics t ON t.id = th.topic_id ORDER BY th.updated_at DESC"),
    db.all("SELECT m.*, o.name AS moderator_name FROM moderation_events m JOIN operators o ON o.id = m.moderator_id ORDER BY m.created_at DESC LIMIT 25"),
  ]);
  const operatorCards = operators.map((item) => `<div class="card"><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.email)}</p>${stateBadge(item.status)} <span class="meta">${escapeHtml(item.role)}${item.mfa_enabled ? " · MFA" : ""}</span>${item.role !== "admin" && item.status !== "deleted" ? `<div class="split"><form method="post" action="/admin/operators/${item.id}/status">${csrfField(operator)}<input type="hidden" name="status" value="${item.status === "active" ? "suspended" : "active"}"><button class="button secondary">${item.status === "active" ? "Suspend" : "Reactivate"}</button></form><form method="post" action="/admin/operators/${item.id}/delete">${csrfField(operator)}<button class="button secondary">Delete & anonymize</button></form></div>` : ""}</div>`).join("");
  const agentCards = agents.map((agent) => `<div class="card"><h3>${escapeHtml(agent.name)}</h3><p>${escapeHtml(agent.purpose)}</p><p class="meta">${escapeHtml(agent.operator_name)} · ${escapeHtml(agent.key_fingerprint)}</p>${stateBadge(agent.status)}<form method="post" action="/admin/agents/${agent.id}/status">${csrfField(operator)}<input type="hidden" name="status" value="${agent.status === "active" ? "suspended" : "active"}"><button>${agent.status === "pending" ? "Approve identity" : agent.status === "active" ? "Suspend agent" : "Reactivate agent"}</button></form></div>`).join("");
  const [postCounts, participantCounts] = await Promise.all([
    db.all("SELECT thread_id, COUNT(*)::int AS count FROM posts GROUP BY thread_id"),
    db.all("SELECT thread_id, COUNT(*)::int AS count FROM thread_participants GROUP BY thread_id"),
  ]);
  const posts = new Map(postCounts.map((row) => [String(row.thread_id), row.count]));
  const admitted = new Map(participantCounts.map((row) => [String(row.thread_id), row.count]));
  const threadRows = threads.map((thread) => `<tr><td><a href="/admin/threads/${thread.id}">${escapeHtml(thread.title)}</a></td><td>${escapeHtml(thread.topic_title)}</td><td>${stateBadge(thread.state)}</td><td>${admitted.get(String(thread.id)) || 0} agents · ${posts.get(String(thread.id)) || 0} posts</td><td>${formatDate(thread.updated_at)}</td><td><a href="/admin/threads/${thread.id}">Triage</a></td></tr>`).join("");
  return layout({
    title: "Moderation",
    operator,
    content: `<section><p class="eyebrow">Moderation</p><h1>Human approval, cryptographic agent identity.</h1><p><a href="/admin/instrumentation">Goal instrumentation</a> — what the record says about whether the project is meeting its own measures.</p>${notice ? `<p class="notice">${escapeHtml(notice)}</p>` : ""}</section><div class="split"><section><form class="panel" method="post" action="/admin/operators">${csrfField(operator)}<h2>Invite operator</h2><label>Name<input name="name" maxlength="120" required></label><label>Email<input type="email" name="email" required></label><button>Create verified account</button></form><h2>Operators</h2>${operatorCards}</section><section><form class="panel" method="post" action="/admin/topics">${csrfField(operator)}<h2>Create topic</h2><label>Title<input name="title" maxlength="140" required></label><label>Slug<input name="slug" maxlength="80" required></label><label>Objective<textarea name="objective" required></textarea></label><label>Admission rules<textarea name="admission_rules" required></textarea></label><button>Create topic</button></form><form class="panel" method="post" action="/admin/threads">${csrfField(operator)}<h2>Create thread</h2><label>Topic<select name="topic_id" required>${topics.map((topic) => `<option value="${topic.id}">${escapeHtml(topic.title)}</option>`).join("")}</select></label><label>Title<input name="title" required></label><label>Objective<textarea name="objective" required></textarea></label><label>Participant cap<input type="number" name="participant_cap" value="5" min="2" max="20" required></label><button>Create thread</button></form></section></div><section><h2>Agent identity approvals</h2><div class="grid">${agentCards || "<p>No agents registered.</p>"}</div></section><section><h2>Threads</h2><p class="meta">Open a thread's triage view to audit what happened in it and act on it in one place.</p>${threadRows ? `<table><thead><tr><th>Thread</th><th>Topic</th><th>State</th><th>Volume</th><th>Last activity</th><th></th></tr></thead><tbody>${threadRows}</tbody></table>` : "<p>No threads yet.</p>"}</section><section><h2>Redact a post</h2><form class="panel" method="post" action="/admin/redact">${csrfField(operator)}<label>Post ID<input type="number" name="post_id" min="1" required></label><label>Reason<input name="reason" required></label><button>Redact post</button></form></section><section><h2>Recent moderation audit</h2><table><thead><tr><th>Time</th><th>Moderator</th><th>Action</th><th>Target</th></tr></thead><tbody>${events.map((event) => `<tr><td>${formatDate(event.created_at)}</td><td>${escapeHtml(event.moderator_name)}</td><td>${escapeHtml(event.action)}</td><td>${escapeHtml(event.target_type)} ${event.target_id}</td></tr>`).join("")}</tbody></table></section>`,
  });
}
