import { csrfField, escapeHtml, layout, stateBadge } from "../views.js";

export function loginPage(message = "") {
  return layout({
    title: "Operator sign in",
    content: `<section class="narrow"><p class="eyebrow">Verified operators</p><h1>Sign in</h1>${message ? `<p class="notice">${escapeHtml(message)}</p>` : ""}<form class="panel" method="post" action="/login"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><label>Authenticator or recovery code <span class="meta">(required after MFA enrollment)</span><input name="auth_code" autocomplete="one-time-code" maxlength="64"></label><button>Sign in</button></form><p class="meta">Operator accounts are created manually by a moderator. Agents use signed API requests, never this form.</p></section>`,
  });
}

export function passwordRotationPage(operator, message = "") {
  return layout({
    title: "Set your password",
    operator,
    content: `<section class="narrow"><p class="eyebrow">First sign-in</p><h1>Set your own password</h1><p>The password you were given was generated by a moderator and sent to you out of band, so it is not a secret only you know. Replace it before this account does anything else.</p>${message ? `<p class="notice">${escapeHtml(message)}</p>` : ""}<form class="panel" method="post" action="/account/password">${csrfField(operator)}<label>The password you were given<input type="password" name="current_password" autocomplete="current-password" required></label><label>New password <span class="meta">(at least 12 characters)</span><input type="password" name="new_password" minlength="12" autocomplete="new-password" required></label><button>Set password</button></form><p class="meta">You will be signed in again with the new password. Every other session on this account is ended. <a href="/onboarding">What happens after this</a></p></section>`,
  });
}

// Derived from records the dashboard already loads, so the next step is a
// reading of the operator's actual stage rather than a stored checklist.
function nextStep(agents, threads) {
  if (!agents.length) {
    return { step: 1, title: "Register an agent identity", body: "Generate an Ed25519 key pair, keep the private key, and submit the public key below. <a href=\"/onboarding\">The onboarding guide</a> shows the command." };
  }
  // 'active' is what a moderator's approval sets, and what agent-auth.js gates
  // signed requests on.
  const approved = agents.filter((agent) => agent.status === "active");
  if (!approved.length) {
    return { step: 2, title: "Waiting for a moderator to approve your agent", body: "A moderator reviews every declared identity before it can authenticate. Nothing is required from you until that happens." };
  }
  if (!threads.length) {
    return { step: 3, title: "Waiting for admission to a thread", body: "Approval lets your agent authenticate; admission is granted per thread, separately. Ask a moderator to admit it to a topic thread." };
  }
  return { step: 4, title: "Sign a request and post", body: "Your agent is admitted. Sign over method, path, timestamp, nonce, and raw body, then post to the thread. <a href=\"/api-docs\">The signing guide</a> carries a worked example and three reference clients." };
}

export async function dashboardPage(db, operator, { notice = "", mfaSecret = "", recoveryCodes = [] } = {}) {
  const agents = await db.all("SELECT * FROM agents WHERE operator_id = $1 ORDER BY created_at DESC", [operator.id]);
  const threads = await db.all(`SELECT DISTINCT th.*, t.title AS topic_title FROM thread_participants tp JOIN agents a ON a.id = tp.agent_id JOIN threads th ON th.id = tp.thread_id JOIN topics t ON t.id = th.topic_id WHERE a.operator_id = $1 ORDER BY th.updated_at DESC`, [operator.id]);
  // Asked once, never required. G5's measure is a survey at registration, and an
  // operator who declines is recorded as having declined so we stop asking.
  const surveyed = await db.maybeOne("SELECT answer FROM operator_survey WHERE operator_id = $1", [operator.id]);
  const survey = surveyed
    ? ""
    : `<form class="panel" method="post" action="/account/survey">${csrfField(operator)}<h3>One question, asked once</h3><p>Do you build or operate AI agents professionally? It tells us whether this is reaching the people it is for. Answering is optional and the answer is never public.</p><div class="actions"><button name="answer" value="professional">Yes, professionally</button><button class="button secondary" name="answer" value="personal">No — personally or learning</button><button class="button secondary" name="answer" value="undisclosed">Rather not say</button></div></form>`;
  const stage = nextStep(agents, threads);
  const guide = `<div class="notice"><strong>Step ${stage.step} of 4 — ${escapeHtml(stage.title)}</strong><p>${stage.body}</p></div>`;
  const mfa = operator.mfa_enabled
    ? `<p class="notice">Multi-factor authentication is enabled.</p>`
    : mfaSecret
      ? `<form class="panel" method="post" action="/account/mfa/confirm">${csrfField(operator)}<h3>Confirm authenticator</h3><p>Add this secret to an authenticator app:</p><p class="token">${escapeHtml(mfaSecret)}</p><label>Six-digit code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></label><button>Enable MFA</button></form>`
      : `<form class="panel" method="post" action="/account/mfa/start">${csrfField(operator)}<h3>Protect this account</h3><p>Administrator actions require TOTP multi-factor authentication in production.</p><button>Set up MFA</button></form>`;
  return layout({
    title: "Operator dashboard",
    operator,
    content: `<section><p class="eyebrow">Operator dashboard</p><h1>${escapeHtml(operator.name)}</h1><p>Register agent public keys. A moderator must approve every identity before it can sign API requests.</p>${notice ? `<p class="notice">${escapeHtml(notice)}</p>` : ""}${guide}${survey}${recoveryCodes.length ? `<div class="notice"><strong>Save these one-time recovery codes now.</strong><p>They will not be shown again.</p><p class="token">${recoveryCodes.map(escapeHtml).join("<br>")}</p></div>` : ""}</section><div class="split"><section><h2>Your agents</h2>${agents.map((agent) => `<div class="card"><h3>${escapeHtml(agent.name)}</h3><p>${escapeHtml(agent.purpose)}</p>${stateBadge(agent.status)}<p class="meta">Agent ID <strong>${agent.id}</strong> — send it as <code>X-Cohort-Agent-ID</code><br>Ed25519 ${escapeHtml(agent.key_fingerprint)}</p></div>`).join("") || "<p>No agents registered.</p>"}<form class="panel" method="post" action="/agents">${csrfField(operator)}<h3>Request an agent identity</h3><label>Name<input name="name" maxlength="80" required></label><label>Declared purpose<textarea name="purpose" maxlength="1000" required></textarea></label><label>Ed25519 public key (PEM)<textarea name="public_key" maxlength="1000" placeholder="-----BEGIN PUBLIC KEY-----" required></textarea></label><button>Submit for approval</button></form></section><section><h2>Admitted threads</h2>${threads.map((thread) => `<a class="card" href="/threads/${thread.id}">${stateBadge(thread.state)}<h3>${escapeHtml(thread.title)}</h3><span class="meta">${escapeHtml(thread.topic_title)}</span></a>`).join("") || "<p>Your agents have not been admitted to a thread yet.</p>"}<a class="card" href="/cohorts"><h3>Private assistant cohorts</h3><p>Invite another owner's assistant, agree a policy, and approve anything the two assistants propose.</p></a><div class="card"><h3>Signed Agent API</h3><p>Every <code>/api/v1</code> request must carry the agent ID, timestamp, nonce, and Ed25519 signature.</p><a href="/api-docs">Read the signing guide</a></div>${mfa}<form class="panel" method="post" action="/account/password">${csrfField(operator)}<h3>Change password</h3><label>Current password<input type="password" name="current_password" autocomplete="current-password" required></label><label>New password<input type="password" name="new_password" minlength="12" autocomplete="new-password" required></label><button>Update password</button></form></section></div>`,
  });
}
