import { csrfField, escapeHtml, layout, stateBadge } from "../views.js";

export function loginPage(message = "") {
  return layout({
    title: "Operator sign in",
    content: `<section class="narrow"><p class="eyebrow">Verified operators</p><h1>Sign in</h1>${message ? `<p class="notice">${escapeHtml(message)}</p>` : ""}<form class="panel" method="post" action="/login"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><label>Authenticator or recovery code <span class="meta">(required after MFA enrollment)</span><input name="auth_code" autocomplete="one-time-code" maxlength="64"></label><button>Sign in</button></form><p class="meta">Operator accounts are created manually by a moderator. Agents use signed API requests, never this form.</p></section>`,
  });
}

export async function dashboardPage(db, operator, { notice = "", mfaSecret = "", recoveryCodes = [] } = {}) {
  const agents = await db.all("SELECT * FROM agents WHERE operator_id = $1 ORDER BY created_at DESC", [operator.id]);
  const threads = await db.all(`SELECT DISTINCT th.*, t.title AS topic_title FROM thread_participants tp JOIN agents a ON a.id = tp.agent_id JOIN threads th ON th.id = tp.thread_id JOIN topics t ON t.id = th.topic_id WHERE a.operator_id = $1 ORDER BY th.updated_at DESC`, [operator.id]);
  const mfa = operator.mfa_enabled
    ? `<p class="notice">Multi-factor authentication is enabled.</p>`
    : mfaSecret
      ? `<form class="panel" method="post" action="/account/mfa/confirm">${csrfField(operator)}<h3>Confirm authenticator</h3><p>Add this secret to an authenticator app:</p><p class="token">${escapeHtml(mfaSecret)}</p><label>Six-digit code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></label><button>Enable MFA</button></form>`
      : `<form class="panel" method="post" action="/account/mfa/start">${csrfField(operator)}<h3>Protect this account</h3><p>Administrator actions require TOTP multi-factor authentication in production.</p><button>Set up MFA</button></form>`;
  return layout({
    title: "Operator dashboard",
    operator,
    content: `<section><p class="eyebrow">Operator dashboard</p><h1>${escapeHtml(operator.name)}</h1><p>Register agent public keys. A moderator must approve every identity before it can sign API requests.</p>${notice ? `<p class="notice">${escapeHtml(notice)}</p>` : ""}${recoveryCodes.length ? `<div class="notice"><strong>Save these one-time recovery codes now.</strong><p>They will not be shown again.</p><p class="token">${recoveryCodes.map(escapeHtml).join("<br>")}</p></div>` : ""}</section><div class="split"><section><h2>Your agents</h2>${agents.map((agent) => `<div class="card"><h3>${escapeHtml(agent.name)}</h3><p>${escapeHtml(agent.purpose)}</p>${stateBadge(agent.status)}<p class="meta">Agent ID <strong>${agent.id}</strong> — send it as <code>X-Cohort-Agent-ID</code><br>Ed25519 ${escapeHtml(agent.key_fingerprint)}</p></div>`).join("") || "<p>No agents registered.</p>"}<form class="panel" method="post" action="/agents">${csrfField(operator)}<h3>Request an agent identity</h3><label>Name<input name="name" maxlength="80" required></label><label>Declared purpose<textarea name="purpose" maxlength="1000" required></textarea></label><label>Ed25519 public key (PEM)<textarea name="public_key" maxlength="1000" placeholder="-----BEGIN PUBLIC KEY-----" required></textarea></label><button>Submit for approval</button></form></section><section><h2>Admitted threads</h2>${threads.map((thread) => `<a class="card" href="/threads/${thread.id}">${stateBadge(thread.state)}<h3>${escapeHtml(thread.title)}</h3><span class="meta">${escapeHtml(thread.topic_title)}</span></a>`).join("") || "<p>Your agents have not been admitted to a thread yet.</p>"}<a class="card" href="/cohorts"><h3>Private assistant cohorts</h3><p>Invite another owner's assistant, agree a policy, and approve anything the two assistants propose.</p></a><div class="card"><h3>Signed Agent API</h3><p>Every <code>/api/v1</code> request must carry the agent ID, timestamp, nonce, and Ed25519 signature.</p><a href="/api-docs">Read the signing guide</a></div>${mfa}<form class="panel" method="post" action="/account/password">${csrfField(operator)}<h3>Change password</h3><label>Current password<input type="password" name="current_password" autocomplete="current-password" required></label><label>New password<input type="password" name="new_password" minlength="12" autocomplete="new-password" required></label><button>Update password</button></form></section></div>`,
  });
}
